#!/bin/bash
#list=`find -name "v05_DYToMuMu_M-20_CT10_TuneZ2_7TeV-powheg-pythia_PU_S6_START42_V11_closure*.out"`
syntax="Syntax ${0} {sampleName}"
if [[ -z ${1} ]]
then
  echo ${syntax}
#  exit 1
fi

list=`find -name "${1}*.out"`

for fichier in $list 
do
	echo "$fichier"
	let "a+=`grep "TOTALnbMuonsAfterID\[0\]" $fichier | cut -f 2`"
	let "a2+=`grep "TOTALnbMuonsAfterID\[0\]" $fichier | cut -f 5`"
	let "b+=`grep "TOTALnbMuonsAfterID\[1\]" $fichier | cut -f 2`"
        let "b2+=`grep "TOTALnbMuonsAfterID\[1\]" $fichier | cut -f 5`"
	let "c+=`grep "TOTALnbMuonsAfterID\[2\]" $fichier | cut -f 2`"
        let "c2+=`grep "TOTALnbMuonsAfterID\[2\]" $fichier | cut -f 5`"
	let "d+=`grep "TOTALnbMuonsAfterID\[3\]" $fichier | cut -f 2`"
        let "d2+=`grep "TOTALnbMuonsAfterID\[3\]" $fichier | cut -f 5`"
	let "e+=`grep "TOTALnbMuonsAfterID\[4\]" $fichier | cut -f 2`"
        let "e2+=`grep "TOTALnbMuonsAfterID\[4\]" $fichier | cut -f 5`"
	let "f+=`grep "TOTALnbMuonsAfterID\[5\]" $fichier | cut -f 2`"
        let "f2+=`grep "TOTALnbMuonsAfterID\[5\]" $fichier | cut -f 5`"
	let "g+=`grep "TOTALnbMuonsAfterID\[6\]" $fichier | cut -f 2`"
        let "g2+=`grep "TOTALnbMuonsAfterID\[6\]" $fichier | cut -f 5`"
	let "h+=`grep "TOTALnbMuonsAfterID\[7\]" $fichier | cut -f 2`"
        let "h2+=`grep "TOTALnbMuonsAfterID\[7\]" $fichier | cut -f 5`"
	let "i+=`grep "TOTALnbMuonsAfterID\[8\]" $fichier | cut -f 2`"
        let "i2+=`grep "TOTALnbMuonsAfterID\[8\]" $fichier | cut -f 5`"
	let "j+=`grep "TOTALnbMuonsAfterID\[9\]" $fichier | cut -f 2`"
        let "j2+=`grep "TOTALnbMuonsAfterID\[9\]" $fichier | cut -f 5`"
	let "k+=`grep "TOTALnbMuonsAfterID\[10\]" $fichier | cut -f 2`"
        let "k2+=`grep "TOTALnbMuonsAfterID\[10\]" $fichier | cut -f 5`"
	let "l+=`grep "TOTALnbMuonsAfterID\[11\]" $fichier | cut -f 2`"
        let "l2+=`grep "TOTALnbMuonsAfterID\[11\]" $fichier | cut -f 5`"

	let "l3+=`grep "TOTALnbDimuonsAfterID\[0\]" $fichier | cut -f 2`"
        let "l4+=`grep "TOTALnbEventsAfterDimuonID\[0\]" $fichier | cut -f 5`"
	let "m+=`grep "TOTALnbDimuonsAfterID\[1\]" $fichier | cut -f 2`"
        let "m2+=`grep "TOTALnbEventsAfterDimuonID\[1\]" $fichier | cut -f 5`"
	let "n+=`grep "TOTALnbDimuonsAfterID\[2\]" $fichier | cut -f 2`"
        let "n2+=`grep "TOTALnbEventsAfterDimuonID\[2\]" $fichier | cut -f 5`"

	let "o+=`grep "TOTALnbPhotonsAfterID\[0\]" $fichier | cut -f 2`"
        let "o2+=`grep "TOTALnbEventsAfterPhotonID\[0\]" $fichier | cut -f 5`"
	let "p+=`grep "TOTALnbPhotonsAfterID\[1\]" $fichier | cut -f 2`"
        let "p2+=`grep "TOTALnbEventsAfterPhotonID\[1\]" $fichier | cut -f 5`"
	let "q+=`grep "TOTALnbPhotonsAfterID\[2\]" $fichier | cut -f 2`"
        let "q2+=`grep "TOTALnbEventsAfterPhotonID\[2\]" $fichier | cut -f 5`"
	let "r1+=`grep "TOTALnbPhotonsAfterID\[3\]" $fichier | cut -f 2`"
        let "r2+=`grep "TOTALnbEventsAfterPhotonID\[3\]" $fichier | cut -f 5`"
	let "s+=`grep "TOTALnbPhotonsAfterID\[4\]" $fichier | cut -f 2`"
        let "s2+=`grep "TOTALnbEventsAfterPhotonID\[4\]" $fichier | cut -f 5`"
	let "t+=`grep "TOTALnbPhotonsAfterID\[5\]" $fichier | cut -f 2`"
        let "t2+=`grep "TOTALnbEventsAfterPhotonID\[5\]" $fichier | cut -f 5`"

	let "u+=`grep "TOTALnbMuMuGammaAfterID\[0\]" $fichier | cut -f 2`"
        let "u2+=`grep "TOTALnbEventsAfterMuMuGammaID\[0\]" $fichier | cut -f 5`"
	let "v+=`grep "TOTALnbMuMuGammaAfterID\[1\]" $fichier | cut -f 2`"
        let "v2+=`grep "TOTALnbEventsAfterMuMuGammaID\[1\]" $fichier | cut -f 5`"
	let "w+=`grep "TOTALnbMuMuGammaAfterID\[2\]" $fichier | cut -f 2`"
        let "w2+=`grep "TOTALnbEventsAfterMuMuGammaID\[2\]" $fichier | cut -f 5`"
	let "x+=`grep "TOTALnbMuMuGammaAfterID\[3\]" $fichier | cut -f 2`"
        let "x2+=`grep "TOTALnbEventsAfterMuMuGammaID\[3\]" $fichier | cut -f 5`"
	let "y+=`grep "TOTALnbMuMuGammaAfterID\[4\]" $fichier | cut -f 2`"
        let "y2+=`grep "TOTALnbEventsAfterMuMuGammaID\[4\]" $fichier | cut -f 5`"
	let "z+=`grep "TOTALnbMuMuGammaAfterID\[5\]" $fichier | cut -f 2`"
        let "z2+=`grep "TOTALnbEventsAfterMuMuGammaID\[5\]" $fichier | cut -f 5`"
	let "alpha+=`grep "TOTALnbMuMuGammaAfterID\[6\]" $fichier | cut -f 2`"
        let "alpha2+=`grep "TOTALnbEventsAfterMuMuGammaID\[6\]" $fichier | cut -f 5`"

	let "beta+=`grep "TOTALnbMuMuGammaAfterID\[7\]" $fichier | cut -f 2`"
        let "beta2+=`grep "TOTALnbEventsAfterMuMuGammaID\[7\]" $fichier | cut -f 5`"

done  
echo "TOTALnbMuonsAfterID[0]= ${a}    TOTALnbEventsAfterMuonID[0]= ${a2}"
echo "TOTALnbMuonsAfterID[1]= ${b}    TOTALnbEventsAfterMuonID[1]= ${b2}"
echo "TOTALnbMuonsAfterID[2]= ${c}    TOTALnbEventsAfterMuonID[2]= ${c2}"
echo "TOTALnbMuonsAfterID[3]= ${d}    TOTALnbEventsAfterMuonID[3]= ${d2}"
echo "TOTALnbMuonsAfterID[4]= ${e}    TOTALnbEventsAfterMuonID[4]= ${e2}"
echo "TOTALnbMuonsAfterID[5]= ${f}    TOTALnbEventsAfterMuonID[5]= ${f2}"
echo "TOTALnbMuonsAfterID[6]= ${g}    TOTALnbEventsAfterMuonID[6]= ${g2}"
echo "TOTALnbMuonsAfterID[7]= ${h}    TOTALnbEventsAfterMuonID[7]= ${h2}"
echo "TOTALnbMuonsAfterID[8]= ${i}    TOTALnbEventsAfterMuonID[8]= ${i2}"
echo "TOTALnbMuonsAfterID[9]= ${j}    TOTALnbEventsAfterMuonID[9]= ${j2}"
echo "TOTALnbMuonsAfterID[10]= ${k}    TOTALnbEventsAfterMuonID[10]= ${k2}"
echo "TOTALnbMuonsAfterID[11]= ${l}    TOTALnbEventsAfterMuonID[11]= ${l2}"
echo ""
echo "TOTALnbDimuonsAfterID[0]= ${l3}    TOTALnbEventsAfterDimuonID[0]= ${l4}"
echo "TOTALnbDimuonsAfterID[1]= ${m}    TOTALnbEventsAfterDimuonID[1]= ${m2}"
echo "TOTALnbDimuonsAfterID[2]= ${n}    TOTALnbEventsAfterDimuonID[2]= ${n2}"
echo ""
echo "TOTALnbPhotonsAfterID[0]= ${o}    TOTALnbEventsAfterPhotonID[0]= ${o2}"
echo "TOTALnbPhotonsAfterID[1]= ${p}    TOTALnbEventsAfterPhotonID[1]= ${p2}"
echo "TOTALnbPhotonsAfterID[2]= ${q}    TOTALnbEventsAfterPhotonID[2]= ${q2}"
echo "TOTALnbPhotonsAfterID[3]= ${r1}    TOTALnbEventsAfterPhotonID[3]= ${r2}"
echo "TOTALnbPhotonsAfterID[4]= ${s}    TOTALnbEventsAfterPhotonID[4]= ${s2}"
echo "TOTALnbPhotonsAfterID[5]= ${t}    TOTALnbEventsAfterPhotonID[5]= ${t2}"
echo ""
echo "TOTALnbMuMuGammaAfterID[0]= ${u}    TOTALnbEventsAfterMuMuGammaID[0]= ${u2}"
echo "TOTALnbMuMuGammaAfterID[1]= ${v}    TOTALnbEventsAfterMuMuGammaID[1]= ${v2}"
echo "TOTALnbMuMuGammaAfterID[2]= ${w}    TOTALnbEventsAfterMuMuGammaID[2]= ${w2}"
echo "TOTALnbMuMuGammaAfterID[3]= ${x}    TOTALnbEventsAfterMuMuGammaID[3]= ${x2}"
echo "TOTALnbMuMuGammaAfterID[4]= ${y}    TOTALnbEventsAfterMuMuGammaID[4]= ${y2}"
echo "TOTALnbMuMuGammaAfterID[5]= ${z}    TOTALnbEventsAfterMuMuGammaID[5]= ${z2}"
echo "TOTALnbMuMuGammaAfterID[6]= ${alpha}    TOTALnbEventsAfterMuMuGammaID[6]= ${alpha2}"
echo ""
echo "TOTALnbMuMuGammaAfterID[7]= ${beta}    TOTALnbEventsAfterMuMuGammaID[7]= ${beta2}"

